import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';

export const LANGUAGES = [
  { key: 'ru', label: 'Русский' },
  { key: 'en', label: 'English' },
];

const STORAGE_KEY = 'fsend_lang';

const DICT = {
  ru: {
    login: 'вход',
    register: 'регистрация',
    forgot: 'забыли пароль',
    username: 'логин',
    password: 'пароль',
    invite: 'инвайт',
    confirm: 'повтор',
    account: 'аккаунт',
    token: 'код',
    newPassword: 'новый',
    signIn: 'войти',
    signingIn: 'входим...',
    createAccount: 'создать аккаунт',
    creating: 'создаём...',
    forgotPassword: 'забыли пароль',
    sendResetCode: 'отправить код',
    sending: 'отправляем...',
    haveCode: 'у меня есть код',
    resetPassword: 'сменить пароль',
    updating: 'обновляем...',
    registerDone: 'Аккаунт создан. Теперь войдите.',
    resetRequestHint: 'Введите email или логин. Если аккаунт найден, код восстановления придёт на email.',
    resetRequestDone: 'Если аккаунт найден, код отправлен на email.',
    resetHint: 'Введите код восстановления и новый пароль.',
    resetDone: 'Пароль изменён. Теперь войдите.',
    invitePlaceholder: 'одноразовый инвайт-код',
    usernamePlaceholder: 'логин',
    minPasswordPlaceholder: 'минимум 8 символов',
    repeatPasswordPlaceholder: 'повтор пароля',
    accountPlaceholder: 'логин или email',
    resetTokenPlaceholder: 'код восстановления',

    chats: 'чаты',
    friends: 'друзья',
    conversations: 'диалоги',
    direct: 'диалог',
    group: 'группа',
    newChat: '+ новый',
    emptyChats: 'пусто. нажмите + новый',
    chooseDialog: 'выберите диалог слева\nили начните новый: [ + новый ]',
    back: 'назад',
    messagesShort: 'сообщ.',
    historyStart: '— начало истории —',
    attachFile: 'прикрепить файл',
    messagePlaceholder: 'введите сообщение и нажмите Enter',
    send: 'отправить',
    friendsEmpty: 'друзей пока нет',
    idle: 'ожидание',
    live: 'в сети',
    connecting: 'соединение...',
    disconnected: 'нет связи',
    onlineNow: 'сейчас в сети',
    online: 'в сети',
    offline: 'не в сети',
    lastSeenPrefix: 'был(а)',
    unknown: 'неизвестно',
    justNow: 'только что',
    minAgo: '{n} мин назад',
    hourAgo: '{n} ч назад',
    dayAgo: '{n} дн назад',
    typing: '{user} печатает',
    friendsDashboard: 'профиль друга',
    message: 'сообщение',
    status: 'статус',
    lastSeen: 'последняя активность',
    accent: 'акцент',
    addFriend: 'добавить друга',
    find: 'поиск',
    friendRequests: 'заявки в друзья',
    wantsFriend: 'хочет добавить вас',
    accept: 'принять',
    defer: 'отложить',
    deferred: 'отложено',
    outgoing: 'исходящие',
    pending: 'ожидает',
    request: 'заявка',
    sent: 'отправлено',
    otherFriends: 'остальные друзья',
    noFriendsYet: 'пока пусто',
    friendSearchPlaceholder: 'логин',
    friendSearchNewPlaceholder: 'логин (мин. 2 символа)',

    settingsTitle: '~/профиль/настройки',
    language: 'язык',
    colorScheme: 'цветовая схема',
    avatar: 'аватар',
    chooseImage: 'выбрать изображение',
    imageTypes: 'png / jpg / webp',
    avatarFrame: 'рамка аватара',
    messageFrame: 'рамка сообщений',
    accentColor: 'акцентный цвет',
    previewMessage: 'привет, это превью сообщения',
    saved: 'сохранено',
    close: 'закрыть',
    save: 'сохранить',
    saving: 'сохраняем...',
    invalidImage: 'Выберите файл изображения',
    noFrame: 'без рамки',
    themeMatrix: 'матрица',
    themeGraphite: 'тёмно-серый',
    themePaper: 'светлая',

    admin: 'админ',
    users: 'пользователи',
    invites: 'инвайты',
    user: 'пользователь',
    msgs: 'сообщ.',
    active: 'активен',
    blocked: 'заблокирован',
    inspect: 'смотреть',
    unblock: 'разблокировать',
    block: 'заблокировать',
    adminMessages: 'сообщения',
    images: 'изображения',
    none: '— нет —',
    note: 'заметка',
    generate: 'создать',
    generatedBusy: '...',
    usedBy: 'использовал',
    created: 'создан',
    used: 'использован',
    free: 'свободен',
    copy: 'копировать',
    notePlaceholder: 'кому/зачем',
    exit: 'выйти',
    appearance: 'настройки',
  },
  en: {
    login: 'login',
    register: 'register',
    forgot: 'forgot',
    username: 'login',
    password: 'password',
    invite: 'invite',
    confirm: 'confirm',
    account: 'account',
    token: 'token',
    newPassword: 'new',
    signIn: 'sign in',
    signingIn: 'authenticating...',
    createAccount: 'create account',
    creating: 'creating...',
    forgotPassword: 'forgot password',
    sendResetCode: 'send reset code',
    sending: 'sending...',
    haveCode: 'i have a code',
    resetPassword: 'reset password',
    updating: 'updating...',
    registerDone: 'Account created. Now sign in.',
    resetRequestHint: 'Enter email or login. If the account exists, a reset code will be sent by email.',
    resetRequestDone: 'If the account exists, a code was sent by email.',
    resetHint: 'Enter the reset code and a new password.',
    resetDone: 'Password changed. Now sign in.',
    invitePlaceholder: 'one-time invite code',
    usernamePlaceholder: 'username',
    minPasswordPlaceholder: 'min 8 characters',
    repeatPasswordPlaceholder: 'repeat password',
    accountPlaceholder: 'username or email',
    resetTokenPlaceholder: 'reset code',

    chats: 'chats',
    friends: 'friends',
    conversations: 'conversations',
    direct: 'direct',
    group: 'group',
    newChat: '+ new',
    emptyChats: 'empty. press + new',
    chooseDialog: 'choose a dialog on the left\nor start a new one: [ + new ]',
    back: 'back',
    messagesShort: 'msg',
    historyStart: '— history starts here —',
    attachFile: 'attach file',
    messagePlaceholder: 'type a message and press Enter',
    send: 'send',
    friendsEmpty: 'no friends yet',
    idle: 'idle',
    live: 'live',
    connecting: 'connecting...',
    disconnected: 'disconnected',
    onlineNow: 'online now',
    online: 'online',
    offline: 'offline',
    lastSeenPrefix: 'last seen',
    unknown: 'unknown',
    justNow: 'just now',
    minAgo: '{n} min ago',
    hourAgo: '{n} h ago',
    dayAgo: '{n} d ago',
    typing: '{user} is typing',
    friendsDashboard: 'friends dashboard',
    message: 'message',
    status: 'status',
    lastSeen: 'last seen',
    accent: 'accent',
    addFriend: 'add friend',
    find: 'find',
    friendRequests: 'friend requests',
    wantsFriend: 'wants to be friends',
    accept: 'accept',
    defer: 'defer',
    deferred: 'deferred',
    outgoing: 'outgoing',
    pending: 'pending',
    request: 'request',
    sent: 'sent',
    otherFriends: 'other friends',
    noFriendsYet: 'empty',
    friendSearchPlaceholder: 'username',
    friendSearchNewPlaceholder: 'username (min. 2 chars)',

    settingsTitle: '~/profile/settings',
    language: 'language',
    colorScheme: 'color scheme',
    avatar: 'avatar',
    chooseImage: 'choose image',
    imageTypes: 'png / jpg / webp',
    avatarFrame: 'avatar frame',
    messageFrame: 'message frame',
    accentColor: 'accent color',
    previewMessage: 'hello, this is a message preview',
    saved: 'saved',
    close: 'close',
    save: 'save',
    saving: 'saving...',
    invalidImage: 'Choose an image file',
    noFrame: 'no frame',
    themeMatrix: 'matrix',
    themeGraphite: 'dark gray',
    themePaper: 'white',

    admin: 'admin',
    users: 'users',
    invites: 'invites',
    user: 'user',
    msgs: 'msgs',
    active: 'active',
    blocked: 'blocked',
    inspect: 'inspect',
    unblock: 'unblock',
    block: 'block',
    adminMessages: 'messages',
    images: 'images',
    none: '— none —',
    note: 'note',
    generate: 'generate',
    generatedBusy: '...',
    usedBy: 'used by',
    created: 'created',
    used: 'used',
    free: 'free',
    copy: 'copy',
    notePlaceholder: 'who/why',
    exit: 'exit',
    appearance: 'settings',
  },
};

const LangCtx = createContext(null);

function readLang() {
  const stored = localStorage.getItem(STORAGE_KEY);
  return LANGUAGES.some((l) => l.key === stored) ? stored : 'ru';
}

export function LangProvider({ children }) {
  const [lang, setLangState] = useState(readLang);

  useEffect(() => {
    document.documentElement.lang = lang;
    localStorage.setItem(STORAGE_KEY, lang);
  }, [lang]);

  const setLang = useCallback((next) => {
    if (LANGUAGES.some((l) => l.key === next)) setLangState(next);
  }, []);

  const t = useCallback((key, vars = {}) => {
    const text = DICT[lang]?.[key] ?? DICT.ru[key] ?? key;
    return Object.entries(vars).reduce(
      (acc, [name, value]) => acc.replaceAll(`{${name}}`, String(value)),
      text
    );
  }, [lang]);

  const value = useMemo(() => ({ lang, setLang, t }), [lang, setLang, t]);
  return <LangCtx.Provider value={value}>{children}</LangCtx.Provider>;
}

export const useLang = () => useContext(LangCtx);
